version: '3.4'

services:
  catalog_read_db:
    container_name: catalog_read_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogReadDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog_read_db:/var/lib/postgresql/data/